Repository k-kudo-hub/error_note_sample, pull requests merged in 2021-05, with the labels that each got.

#52 ログイン済みのユーザーしか機能を使えないよう制限
  app/controllers/logs_controller.rb
  app/controllers/stocks_controller.rb
  app/views/logs/show.html.erb
Labels: backend

#59 プログラミング言語一覧の初期データを投入
  app/controllers/logs_controller.rb
  db/migrate/20210504125630_define_languages.rb
  db/schema.rb
Labels: backend

#61 Ruby on Railsを6.1.3.2へアップデート
  Gemfile
  Gemfile.lock
Labels: backend, bug

#33 WIP:静的解析ツールrubocopを追加
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/logs_controller.rb
  app/controllers/stocks_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/logs_helper.rb
  app/helpers/users_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/language.rb
  app/models/log.rb
  app/models/log_language.rb
  app/models/stock.rb
  app/models/user.rb
  app/uploaders/picture_uploader.rb
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookies_serializer.rb
  config/initializers/devise.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/permissions_policy.rb
  config/initializers/wrap_parameters.rb
  config/puma.rb
  config/routes.rb
  config/spring.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/logs_controller_test.rb
  test/controllers/users_controller_test.rb
  test/models/log_test.rb
  test/models/user_test.rb
  test/test_helper.rb
Labels: backend

#58 ログ一覧のデザインを全面的に見直し
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/logs.scss
  app/assets/stylesheets/normarize.scss
  app/assets/stylesheets/shared.scss
  app/controllers/application_controller.rb
  app/controllers/logs_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/helpers/users_helper.rb
  app/models/language.rb
  app/models/user.rb
  app/views/logs/_table.html.erb
  app/views/shared/_header.html.erb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  bin/spring
  bin/webpack
  bin/webpack-dev-server
  bin/yarn
  db/migrate/20210318115336_devise_create_users.rb
  db/migrate/20210318115702_add_columns_to_users.rb
  db/migrate/20210319102348_create_logs.rb
  db/migrate/20210319121028_add_title_to_logs.rb
  db/migrate/20210420144813_create_languages.rb
  db/migrate/20210420150106_create_log_languages.rb
  db/migrate/20210420151751_insert_initial_language.rb
  db/migrate/20210420153943_remove_language_to_logs.rb
  db/migrate/20210421103946_remove_environment_to_logs.rb
  db/migrate/20210421113804_replace_logs_columns.rb
  db/migrate/20210422142726_create_stocks.rb
  db/migrate/20210430113609_replace_users_columns.rb
  db/migrate/20210504125630_define_languages.rb
  db/schema.rb
  db/seeds.rb
  test/channels/application_cable/connection_test.rb
  test/test_helper.rb
Labels: Phase1.5, frontend

#64 非公開のログは表示しないように設定した
  app/controllers/application_controller.rb
  app/controllers/logs_controller.rb
  app/controllers/users_controller.rb
  app/models/language.rb
  app/models/log.rb
  app/models/user.rb
  test/channels/application_cable/connection_test.rb
Labels: frontend

#67 サイドバーの導入
  app/assets/stylesheets/colors.scss
  app/assets/stylesheets/logs.scss
  app/assets/stylesheets/shared.scss
  app/controllers/logs_controller.rb
  app/models/language.rb
  app/views/logs/index.html.erb
Labels: frontend

#71 リファクタリング#65
  Gemfile
  Gemfile.lock
  app/controllers/stocks_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/controllers/users_controller.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/language.rb
  app/views/users/index.html.erb
  config/routes.rb
  test/controllers/.keep
  test/controllers/logs_controller_test.rb
  test/controllers/users_controller_test.rb
  test/fixtures/logs.yml
  test/fixtures/users.yml
  test/models/log_test.rb
  test/models/user_test.rb
Labels: backend

#73 rubocopの警告基準W以上を表示できるrakeタスクを定義
  lib/tasks/rubocop.rake
Labels: Phase1.5, backend

#75 ログ詳細画面のスタイルを見直した
  app/assets/stylesheets/logs.scss
  app/assets/stylesheets/shared.scss
  app/views/logs/search.html.erb
  app/views/logs/show.html.erb
  app/views/users/show.html.erb
Labels: frontend

#80 言語・ストックランキングのVue化
  app/controllers/api/v1/logs_controller.rb
  app/controllers/logs_controller.rb
  app/helpers/api/v1/logs_helper.rb
  app/javascript/app.vue
  app/javascript/packs/hello_vue.js
  app/javascript/packs/user_rank.js
  app/javascript/userRank.vue
  app/models/log.rb
  app/views/layouts/application.html.erb
  app/views/logs/index.html.erb
  config/routes.rb
  package.json
  yarn.lock
Labels: Phase2, frontend

#83 新規ノート作成ページのVue化
  app/controllers/api/v1/languages_controller.rb
  app/controllers/api/v1/log_languages_controller.rb
  app/controllers/api/v1/logs_controller.rb
  app/controllers/api/v1/stocks_controller.rb
  app/helpers/api/v1/languages_helper.rb
  app/helpers/api/v1/log_languages_helper.rb
  app/helpers/api/v1/stocks_helper.rb
  app/javascript/logsCreate.vue
  app/javascript/packs/application.js
  app/javascript/packs/logs_create.js
  app/javascript/userRank.vue
  app/views/layouts/application.html.erb
  app/views/shared/_header.html.erb
  config/routes.rb
  package-lock.json
  package.json
Labels: Phase2, frontend

#87 トップページ・ヘッダー・フッターのVue化
  app/assets/stylesheets/logs.scss
  app/assets/stylesheets/shared.scss
  app/controllers/api/v1/logs_controller.rb
  app/controllers/api/v1/stocks_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/helpers/api/v1/users_helper.rb
  app/javascript/App.vue
  app/javascript/components/Footer.vue
  app/javascript/components/Header.vue
  app/javascript/components/LogsCreate.vue
  app/javascript/components/LogsIndex.vue
  app/javascript/components/UserRank.vue
  app/javascript/packs/logs_create.js
  app/javascript/packs/main.js
  app/models/log.rb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/logs/edit.html.erb
  app/views/logs/index.html.erb
  app/views/logs/new.html.erb
  app/views/logs/search.html.erb
  app/views/logs/show.html.erb
  app/views/users/show.html.erb
  config/locales/ja.yml
  config/routes.rb
  package-lock.json
  package.json
Labels: Phase2, frontend
